"use strict";
let car = 'subaru';
//Test 1 Equality comparison (True)
//console.log("Is car == 'subaru'? I predict True.")
//console.log(car == 'subaru')
//Test 2 Strict equality comparison (True)
//console.log("Is car === 'subaru'? I predict True.")
//console.log(car === 'subaru')
//Test 3 Inequal comparison (False)
//console.log("Is car != 'subaru'? I predict False.")
//console.log(car != 'subaru')
//Test 4 Strick equality comparison (False)
//console.log("Is car !== 'subaru'? I predict False.")
//console.log(car !== 'subaru')
//Test 5 Less than comparison (False)
//console.log("Is car < 'subaru'? I predict False.")
//console.log(car < 'subaru')
//Test 6 Greater than comparison (False)
//console.log("Is car > 'subaru'? I predict False.")
//console.log(car > 'subaru')
//Test 7 Less than or equal comparison (True)
//console.log("Is car <= 'subaru'? I predict True.")
//console.log(car <= 'subaru')
//Test 8 Greater than or equal comparison (True)
//console.log("Is car >= 'subaru'? I predict True.")
//console.log(car >= 'subaru')
//Test 9 Checking Truthiness (True)
console.log("Is car? I predict True.");
console.log(car);
